server:
  port: 8092
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=LEGACY;
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    drop-first: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
