server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CleverEmployee
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    drop-first: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create-drop
#spring.session.jdbc.initialize-schema: always